### ISSUE TITLE
installing rqt_pr2_dashboard from debs pulls in the old rqt_param plugin

### ISSUE THREAD

**Issue by ablasdel** [PR2/rqt_pr2_dashboard#1]

**Comment by dirk-thomas** [comment]
That deb does not depend on rqt_param. See except from the control file:
`Depends: ros-groovy-common-msgs (= 1.9.11-0precise-20121218-0859-+0000), ros-groovy-pr2-common (= 1.10.2-s1355975482~precise), ros-groovy-pr2-power-drivers (= 1.0.9-s1355975994~precise), ros-groovy-ros (= 1.9.36-0precise-20121218-1812-+0000), ros-groovy-ros-comm (= 1.9.37-0precise-20121218-1815-+0000), ros-groovy-rqt (= 0.1.7-s1355976562~precise), ros-groovy-std-msgs (= 0.5.7-0precise-20121218-0844-+0000), libc6, build-essential, cmake, python-yaml, subversion`

**Comment by ablasdel** [comment]
But at the moment it depends on rqt. And the deb out there is 1.7 which has
rqt_param in it.

So it gets installed. When that Debian gets purged and/or we no longer
depend on rqt this will go away

On Dec 21, 2012, at 17:19, Dirk Thomas notifications@github.com wrote:

That deb does not depend on rqt_param. See except from the control file:
Depends: ros-groovy-common-msgs (= 1.9.11-0precise-20121218-0859-+0000),
ros-groovy-pr2-common (= 1.10.2-s1355975482~precise),
ros-groovy-pr2-power-drivers (= 1.0.9-s1355975994~precise), ros-groovy-ros
(= 1.9.36-0precise-20121218-1812-+0000), ros-groovy-ros-comm (=
1.9.37-0precise-20121218-1815-+0000), ros-groovy-rqt (=
0.1.7-s1355976562~precise), ros-groovy-std-msgs (=
0.5.7-0precise-20121218-0844-+0000), libc6, build-essential, cmake,
python-yaml, subversion

—
Reply to this email directly or view it on
GitHubhttps://github.com/ros-visualization/rqt_pr2_dashboard/issues/1#issuecomment-11632094.

**Comment by dirk-thomas** [comment]
The dependency on "rqt" has already been fixed to "rqt_robot". And even "rqt" did not depend on "rqt_param":

`Depends: ros-groovy-ros (= 1.9.36-0oneiric-20121218-0846-+0000), ros-groovy-common-msgs (= 1.9.11-0oneiric-20121218-0902-+0000), ros-groovy-geometry (= 1.9.26-0oneiric-20121218-0928-+0000), ros-groovy-geometry-experimental (= 0.2.4-s1355832704~oneiric), ros-groovy-image-common (= 1.9.22-0oneiric-20121219-0538-+0000), ros-groovy-nodelet-core (= 1.7.12-0oneiric-20121219-2209-+0000), ros-groovy-qt-gui-core (= 0.2.8-0oneiric-20121219-0531-+0000), ros-groovy-ros-comm (= 1.9.37-0oneiric-20121218-1042-+0000), ros-groovy-std-msgs (= 0.5.7-0oneiric-20121218-0842-+0000), ros-groovy-vision-opencv (= 1.9.13-0oneiric-20121218-0912-+0000), ros-groovy-visualization (= 1.9.2-s1355897929~oneiric), ros-groovy-pr2-power-drivers (= 1.0.9-s1355977894~oneiric), python-rospkg, python-matplotlib, python-opengl, python-qt4-gl, python-qwt5-qt4, libc6, build-essential, cmake, python-yaml, subversion`
