### ISSUE TITLE
Consider moving back rqt_pr2_dashboard to robot_plugins

### ISSUE THREAD

**Issue by 130s** [PR2/rqt_pr2_dashboard#11]
AFAIK this pkg became unary stack since some pkgs it depends were not wet back then thus this pkgs remained dry (I guess [in this commit](09aea65e324daf199f85794b5ca983358421e01f)). Now it's catkinized, why not moving this back I suppose to `rqt_robot_plugins`? That makes maintenance work easier.

**Comment by ablasdel** [comment]
It would probably be better to keep it separate. Otherwise robot_plugins would have to depend on all the pr2 stuff.

That wouldn't be ideal.

**Comment by 130s** [comment]
I guess I disagree. robot_plugins would depend on PR2 stuff only indirectly. Actually similar things are already happening; for example, `rqt_rviz` depends on `RViz` while no other plugin needs `RViz`.

Am I missing something?

**Comment by tfoote** [comment]
PR2 is a specific robot with a lot of non generic dependencies.  Rviz is a
generic visualization tool they are not comparable.

**Comment by 130s** [comment]
I got it. Closing.

Now I'm tempted to move this package to `PR2` package (maybe `pr2_common`? I'm not sure. I assume `pr2_gui` is reaching EOL) although it may not be urgent at all.
