### ISSUE TITLE
Extract common functionalities from separate PR2 specific parts

### ISSUE THREAD

**Issue by 130s** [PR2/rqt_pr2_dashboard#12]
Layout and how it aggregates other GUI plugins is nice. I want to utilize it for another robot's GUI that I've been working on recently.

I will separate the portions that depend on PR2 specific messages and components (`pr2_power_board` and what else?), and move generic portions to common plugin metapkg (`rqt_robot_plugins`).

**Comment by ablasdel** [comment]
Which generic functional bits were you thinking of splitting out? Most of this is pretty PR2 specific.

**Comment by 130s** [comment]
Everything; I don't see any GUI components on pr2_dashboard is PR2 specific (though it's internal logic should be). That said what I propose can be to separate its GUI and logic.

However, it turned out the dashboard GUI our team needs looks different from what pr2_dashboard and thus I don't start working on this soon and unassign myself.

**Comment by dirk-thomas** [comment]
rqt_pr2_dashboard already extends rqt_robot_dashboard which contains the majority of the generic implementation.

Without any further information provided this ticket is not clear enough to stay open. Therefore I will close until specific shortcomings of the separation is pointed out and a need is there to refactor it.

**Comment by ablasdel** [comment]
I agree. If individual features are pointed out as general they could be
slated for migration into the robot_dashboard proper.

On Saturday, August 17, 2013, Dirk Thomas wrote:

> rqt_pr2_dashboard already extends rqt_robot_dashboard which contains the
> majority of the generic implementation.
> 
> Without any further information provided this ticket is not clear enough
> to stay open. Therefore I will close until specific shortcomings of the
> separation is pointed out and a need is there to refactor it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-visualization/rqt_pr2_dashboard/issues/12#issuecomment-22816447
> .

## 

Sent from Gmail Mobile

**Comment by 130s** [comment]
Nice to know about `rqt_robot_dashboard`.

Now my suggestion is more concrete; how about moving [PR2Battery](https://github.com/ros-visualization/rqt_pr2_dashboard/blob/eadfc2352b6099be53c4f8b15f73dc05d62f91d2/src/rqt_pr2_dashboard/pr2_battery.py), [PR2Motors](https://github.com/ros-visualization/rqt_pr2_dashboard/blob/eadfc2352b6099be53c4f8b15f73dc05d62f91d2/src/rqt_pr2_dashboard/pr2_motors.py) and [PR2Runstops](https://github.com/ros-visualization/rqt_pr2_dashboard/blob/eadfc2352b6099be53c4f8b15f73dc05d62f91d2/src/rqt_pr2_dashboard/pr2_runstop.py) to `rqt_robot_dashboard` (or any other more common place)? Those classes don't seem to use any PR2 specific information. One downside might be that this can be considered as API break (although I'm not quite sure if there are packages that depend on this package).

I'm writing a dashboard for a humanoid by copy-paste-modify PR2 dashboard. And with those classes being in more common package would make my work far more uniformed. Thanks for consideration!

**Comment by dirk-thomas** [comment]
With our resources it is highly unlikely that we will spend any time on such a refactoring.

If the refactoring is beneficial for your case please consider creating a pull request for both repos which modifies the code base in a way that these parts can be easier reused.

**Comment by ablasdel** [comment]
I also don't have much time to work on this but here is my input:

PR2Battery: I'm not sure how general purpose this is, it takes a pr2_msgs.PowerState message as input...

PR2Runstops: Well not every robot is going to have a wireless and hard run stop. Further if they do they may not interact in the same manner as the PR2 runstops do. I would say this one is probably not as is. But I would be ok with having a more general "Physical runstop" and "wireless runstop" at the higher level. Those separately would be very useful. The code would be very similar to the PR2Runstops with fewer states.

PR2Motors: This one makes the most sense. I would be 100% behind a refactor that made this a generic robot widget and just set PR2 to use the generic one.

**Comment by 130s** [comment]
Thanks for the input you two. Then I'll open a pull request hopefully today.
@ablasdel that's valuable. What I will probably do if necessary is to create abstract or default implementation classes in `robot_dashboard` and have classes in `pr2_dashboard` extend them.

**Comment by ablasdel** [comment]
I think that is a very good idea and it would make it more useful. I look forward to it!
