### ISSUE TITLE
Moving this to the pr2 repo

### ISSUE THREAD

**Issue by UltronDestroyer** [PR2/rqt_pr2_dashboard#16]
Do you think this would fit better in the github.com/PR2/ repo? The maintainership can then be brought unto myself.

**Comment by tfoote** [comment]
I think it makes sense to move it there. Thoughts anyone else?

**Comment by 130s** [comment]
+1

**Comment by ablasdel** [comment]
+1 I am probably no longer a good person to maintain this as I won't have pr2 access for the foreseeable future. I want to note that the rqt_pr2_dashboard portion of the code isn't where the meat of the functionality(and bugs) is(are). The general purpose buttons that the dashboard uses (monitor and console) are and should probably stay in rqt_robot_plugins. Most of the problems you are probably hoping to fix exist in the robot_monitor plugin and are well documented on the rqt_robot_plugins repo. Would you be interested in maintaining the robot monitor plugin as well?

**Comment by ablasdel** [comment]
Somehow in the book I wrote I forgot to mention that yes this should definitely be moved if only to make it slightly easier to install/use a pr2.

**Comment by ablasdel** [comment]
also my author email should probably be changed from ablasdel@willowgarage.com so it isn't just a black hole. I will make that fix in preparation for the transfer.

If you need any help/clarification of what is going on feel free to drop me a line at any time.

**Comment by UltronDestroyer** [comment]
Here ye here ye. All in unanimous motion to transfer rqt_pr2_dashboard! _smashes mallet_. Onforth with ye' days.

**Comment by ablasdel** [comment]
I'll be back from IROS next week and I'll get moving on this if nobody else beats me to the punch. 

Dash if you want to pull request the package.xml maintainership changes can merge those. Wouldn't want to change it myself and use the wrong email.

**Comment by UltronDestroyer** [comment]
Ok, will do. Have fun this week at IROS.

**Comment by ablasdel** [comment]
Scratch that! Looks like it is good to go now. @tfoote can you merge https://github.com/ros/rosdistro/pull/5816 when you get a free moment so the next build doesn't blow up?

**Comment by ablasdel** [comment]
rosdistro is updated so the hand off is complete. Dash if there is any trouble ping me. I'm closing this.

**Comment by dirk-thomas** [comment]
I will release the current state into Hydro which only includes the updated maintainer (681d9c23e602d10b374e30a1a67701d354cb7b70) compared to the last release.

I am actually not doing this to get the updated maintainer out but to test a modified bloom version :wink:  If the job will fail because of that I will of course address it. I hope that is ok with you guys.

**Comment by UltronDestroyer** [comment]
Sounds good.
