### ISSUE TITLE
Can't disable breakers from dashboard

### ISSUE THREAD

**Issue by ahendrix** [PR2/rqt_pr2_dashboard#2]
Clicking 'disable' or 'disable all breakers' on the breaker icons does not disable the breakers. This is a problem because it is the only way to force the motor controllers to recalibrate aside from powering the robot all the way off.

**Comment by ablasdel** [comment]
When I tested this with the robots running fuerte it worked. Or at least
the pr2 reported it was disabled after doing so in the dashboard.

I assume you are running groovy and the robot is too?

Does the button change color after the disable?
