### ISSUE TITLE
High CPU load warning is inaccurate?

### ISSUE THREAD

**Issue by jon-weisz** [PR2/rqt_pr2_dashboard#4]
I am getting high CPU load warnings for both c1 and c2 on PR-N, even though the load is not what I would call critically high on either

mpstat on c1:
03:30:56 PM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest   %idle
03:30:57 PM  all   53.68    0.00   15.35    0.00    0.00    4.65    0.00    0.00   26.32
Average:     all   53.68    0.00   15.35    0.00    0.00    4.65    0.00    0.00   26.32

mpstat on c2:
jweisz@prn2:~$ mpstat 1 1
Linux 3.4.4.rt13-2-pr2 (prn2)   01/20/2013      _x86_64_        (8 CPU)

03:28:52 PM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest   %idle
03:28:53 PM  all   35.08    0.00    3.00    0.00    0.00    0.75    0.00    0.00   61.17
Average:     all   35.08    0.00    3.00    0.00    0.00    0.75    0.00    0.00   61.17

**Comment by 130s** [comment]
I think in general we'll appreciate if you could provide the reason to close an issue so that we can look back when someone hits a similar/same issue.

**Comment by ablasdel** [comment]
The issue is not related to rqt_pr2_dashboard. It was just a warning that came up IN rqt_pr2_dashboard.
