### ISSUE TITLE
Double free in rqt_pr2_dashboard.

### ISSUE THREAD

**Issue by ahendrix** [PR2/rqt_pr2_dashboard#5]
Running /etc/ros/robot.launch, motors enabled.

$ dpkg -l ros-groovy-rqt-pr2-dashboard ros-groovy-rqt ros-groovy-qt-gui-core
ii  ros-groovy-qt-gui-core      0.2.9-0precise-20121230-111
ii  ros-groovy-rqt              0.2.7-0precise-20121231-195
ii  ros-groovy-rqt-pr2-dashboar 0.2.2-s1357263675~precise

**\* glibc detected **\* /usr/bin/python: double free or corruption (fasttop): 0x00007f0314240b30 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7eb96)[0x7f03552ebb96]
/usr/lib/nvidia-current/tls/libnvidia-tls.so.304.43(+0x1cc1)[0x7f034b1decc1]
======= Memory map: ========
00400000-00671000 r-xp 00000000 08:02 10797                              /usr/bin/python2.7
00870000-00871000 r--p 00270000 08:02 10797                              /usr/bin/python2.7
00871000-008da000 rw-p 00271000 08:02 10797                              /usr/bin/python2.7
008da000-008ec000 rw-p 00000000 00:00 0 
02225000-06403000 rw-p 00000000 00:00 0                                  [heap]
7f02fc000000-7f02fc021000 rw-p 00000000 00:00 0 
7f02fc021000-7f0300000000 ---p 00000000 00:00 0 
7f0300000000-7f030026b000 rw-p 00000000 00:00 0 
7f030026b000-7f0304000000 ---p 00000000 00:00 0 
7f0304000000-7f0304022000 rw-p 00000000 00:00 0 
7f0304022000-7f0308000000 ---p 00000000 00:00 0 
7f0309ac6000-7f0309ac7000 ---p 00000000 00:00 0 
7f0309ac7000-7f030a2c7000 rw-p 00000000 00:00 0 
7f030a2c7000-7f030a2c8000 ---p 00000000 00:00 0 
7f030a2c8000-7f030aac8000 rw-p 00000000 00:00 0 
7f030aac8000-7f030ab29000 r-xp 00000000 08:02 8066                       /usr/lib/x86_64-linux-gnu/libtiff.so.4.3.4
7f030ab29000-7f030ad28000 ---p 00061000 08:02 8066                       /usr/lib/x86_64-linux-gnu/libtiff.so.4.3.4
7f030ad28000-7f030ad2a000 r--p 00060000 08:02 8066                       /usr/lib/x86_64-linux-gnu/libtiff.so.4.3.4
7f030ad2a000-7f030ad2b000 rw-p 00062000 08:02 8066                       /usr/lib/x86_64-linux-gnu/libtiff.so.4.3.4
7f030ad2b000-7f030ad32000 r-xp 00000000 08:02 17460                      /usr/lib/x86_64-linux-gnu/qt4/plugins/imageformats/libqtiff.so
7f030ad32000-7f030af31000 ---p 00007000 08:02 17460                      /usr/lib/x86_64-linux-gnu/qt4/plugins/imageformats/libqtiff.so
7f030af31000-7f030af32000 r--p 00006000 08:02 17460                      /usr/lib/x86_64-linux-gnu/qt4/plugins/imageformats/libqtiff.so
7f030af32000-7f030af33000 rw-p 00007000 08:02 17460                      /usr/lib/x86_64-linux-gnu/qt4/plugins/imageformats/libqtiff.so
7f030af33000-7f030af38000 r-xp 00000000 08:02 25877                      /usr/lib/x86_64-linux-gnu/qt4/plugins/imageformats/libqsvg.so
7f030af38000-7f030b137000 ---p 00005000 08:02 25877                      /usr/lib/x86_64-linux-gnu/qt4/plugins/imageformats/libqsvg.so
7f030b137000-7f030b138000 r--p 00004000 08:02 25877                      /usr/lib/x86_64-linux-gnu/qt4/plugins/imageformats/libqsvg.so
7f030b138000-7f030b139000 rw-p 00005000 08:02 25877                      /usr/lib/x86_64-linux-gnu/qt4/plugins/imageformats/libqsvg.so
7f030b139000-7f030b16c000 r-xp 00000000 08:02 17051                      /usr/lib/x86_64-linux-gnu/liblcms.so.1.0.19
7f030b16c000-7f030b36c000 ---p 00033000 08:02 17051                      /usr/lib/x86_64-linux-gnu/liblcms.so.1.0.19
7f030b36c000-7f030b36d000 r--p 00033000 08:02 17051                      /usr/lib/x86_64-linux-gnu/liblcms.so.1.0.19
7f030b36d000-7f030b36e000 rw-p 00034000 08:02 17051                      /usr/lib/x86_64-linux-gnu/liblcms.so.1.0.19
7f030b36e000-7f030b370000 rw-p 00000000 00:00 0 
7f030b370000-7f030b3f3000 r-xp 00000000 08:02 17053                      /usr/lib/x86_64-linux-gnu/libmng.so.1.1.0.10
7f030b3f3000-7f030b5f3000 ---p 00083000 08:02 17053                      /usr/lib/x86_64-linux-gnu/libmng.so.1.1.0.10
7f030b5f3000-7f030b5f6000 r--p 00083000 08:02 17053                      /usr/lib/x86_64-linux-gnu/libmng.so.1.1.0.10
7f030b5f6000-7f030b5f8000 rw-p 00086000 08:02 17053                      /usr/lib/x86_64-linux-gnu/libmng.so.1.1.0.10
7f030b5f8000-7f030b5fd000 r-xp 00000000 08:02 17919                      /usr/lib/x86_64-linux-gnu/qt4/plugins/imageformats/libqmng.so
7f030b5fd000-7f030b7fd000 ---p 00005000 08:02 17919                      /usr/lib/x86_64-linux-gnu/qt4/plugins/imageformats/libqmng.so
7f030b7fd000-7f030b7fe000 r--p 00005000 08:02 17919                      /usr/lib/x86_64-linux-gnu/qt4/plugins/imageformats/libqmng.so
7f030b7fe000-7f030b7ff000 rw-p 00006000 08:02 17919                      /usr/lib/x86_64-linux-gnu/qt4/plugins/imageformats/libqmng.so
7f030b7ff000-7f030b800000 ---p 00000000 00:00 0 
7f030b800000-7f030c000000 rw-p 00000000 00:00 0 
7f030c000000-7f030c10e000 rw-p 00000000 00:00 0 
7f030c10e000-7f0310000000 ---p 00000000 00:00 0 
7f0310010000-7f03102d0000 rw-s 00000000 00:04 2195486                    /SYSV00000000 (deleted)
7f03102d0000-7f031031a000 r-xp 00000000 08:02 44524                      /usr/lib/qt4/plugins/designer/kdewidgets.so
7f031031a000-7f0310519000 ---p 0004a000 08:02 44524                      /usr/lib/qt4/plugins/designer/kdewidgets.so
7f0310519000-7f0310522000 r--p 00049000 08:02 44524                      /usr/lib/qt4/plugins/designer/kdewidgets.so
7f0310522000-7f0310523000 rw-p 00052000 08:02 44524                      /usr/lib/qt4/plugins/designer/kdewidgets.so
7f0310523000-7f0310544000 r-xp 00000000 08:02 27276                      /usr/lib/libkdewebkit.so.5.8.0
7f0310544000-7f0310744000 ---p 00021000 08:02 27276                      /usr/lib/libkdewebkit.so.5.8.0
7f0310744000-7f0310745000 r--p 00021000 08:02 27276                      /usr/lib/libkdewebkit.so.5.8.0
7f0310745000-7f0310746000 rw-p 00022000 08:02 27276                      /usr/lib/libkdewebkit.so.5.8.0
7f0310746000-7f031074b000 r-xp 00000000 08:02 44523                      /usr/lib/qt4/plugins/designer/kdewebkitwidgets.so
7f031074b000-7f031094b000 ---p 00005000 08:02 44523                      /usr/lib/qt4/plugins/designer/kdewebkitwidgets.so
7f031094b000-7f031094c000 r--p 00005000 08:02 44523                      /usr/lib/qt4/plugins/designer/kdewebkitwidgets.so
7f031094c000-7f031094d000 rw-p 00006000 08:02 44523                      /usr/lib/qt4/plugins/designer/kdewebkitwidgets.so
7f031094d000-7f0310953000 r-xp 00000000 08:02 44525                      /usr/lib/qt4/plugins/designer/kdedeprecated.so
7f0310953000-7f0310b53000 ---p 00006000 08:02 44525                      /usr/lib/qt4/plugins/designer/kdedeprecated.so
7f0310b53000-7f0310b54000 r--p 00006000 08:02 44525                      /usr/lib/qt4/plugins/designer/kdedeprecated.so
7f0310b54000-7f0310b55000 rw-p 00007000 08:02 44525                      /usr/lib/qt4/plugins/designer/kdedeprecated.so
7f0310b55000-7f0310b8a000 r-xp 00000000 08:02 27244                      /usr/lib/libstreams.so.0.7.7
7f0310b8a000-7f0310d89000 ---p 00035000 08:02 27244                      /usr/lib/libstreams.so.0.7.7
7f0310d89000-7f0310d8b000 r--p 00034000 08:02 27244                      /usr/lib/libstreams.so.0.7.7
7f0310d8b000-7f0310d8c000 rw-p 00036000 08:02 27244                      /usr/lib/libstreams.so.0.7.7
7f0310d8c000-7f0310dd3000 r-xp 00000000 08:02 27269                      /usr/lib/libnepomukquery.so.4.8.0
7f0310dd3000-7f0310fd3000 ---p 00047000 08:02 27269                      /usr/lib/libnepomukquery.so.4.8.0
7f0310fd3000-7f0310fd4000 r--p 00047000 08:02 27269                      /usr/lib/libnepomukquery.so.4.8.0
7f0310fd4000-7f0310fd5000 rw-p 00048000 08:02 27269                      /usr/lib/libnepomukquery.so.4.8.0
7f0310fd5000-7f0311023000 r-xp 00000000 08:02 27233                      /usr/lib/libsopranoclient.so.1.2.0
7f0311023000-7f0311223000 ---p 0004e000 08:02 27233                      /usr/lib/libsopranoclient.so.1.2.0
7f0311223000-7f0311225000 r--p 0004e000 08:02 27233                      /usr/lib/libsopranoclient.so.1.2.0
7f0311225000-7f0311226000 rw-p 00050000 08:02 27233                      /usr/lib/libsopranoclient.so.1.2.0
7f0311226000-7f0311314000 r-xp 00000000 08:02 27232                      /usr/lib/libsoprano.so.4.3.0
7f0311314000-7f0311513000 ---p 000ee000 08:02 27232                      /usr/lib/libsoprano.so.4.3.0
7f0311513000-7f0311519000 r--p 000ed000 08:02 27232                      /usr/lib/libsoprano.so.4.3.0
7f0311519000-7f031151a000 rw-p 000f3000 08:02 27232                      /usr/lib/libsoprano.so.4.3.0
7f031151a000-7f031151e000 r-xp 00000000 08:02 66                         /lib/x86_64-linux-gnu/libattr.so.1.1.0
7f031151e000-7f031171d000 ---p 00004000 08:02 66                         /lib/x86_64-linux-gnu/libattr.so.1.1.0
7f031171d000-7f031171e000 r--p 00003000 08:02 66                         /lib/x86_64-linux-gnu/libattr.so.1.1.0
7f031171e000-7f031171f000 rw-p 00004000 08:02 66                         /lib/x86_64-linux-gnu/libattr.so.1.1.0
7f031171f000-7f0311726000 r-xp 00000000 08:02 63                         /lib/x86_64-linux-gnu/libacl.so.1.1.0
7f0311726000-7f0311925000 ---p 00007000 08:02 63                         /lib/x86_64-linux-gnu/libacl.so.1.1.0
7f0311925000-7f0311926000 r--p 00006000 08:02 63                         /lib/x86_64-linux-gnu/libacl.so.1.1.0
7f0311926000-7f0311927000 rw-p 00007000 08:02 63                         /lib/x86_64-linux-gnu/libacl.so.1.1.0
7f0311927000-7f0311a09000 r-xp 00000000 08:02 27255                      /usr/lib/libsolid.so.4.8.0
7f0311a09000-7f0311c08000 ---p 000e2000 08:02 27255                      /usr/lib/libsolid.so.4.8.0
7f0311c08000-7f0311c1c000 r--p 000e1000 08:02 27255                      /usr/lib/libsolid.so.4.8.0
7f0311c1c000-7f0311c1d000 rw-p 000f5000 08:02 27255                      /usr/lib/libsolid.so.4.8.0
7f0311c1d000-7f0311c97000 r-xp 00000000 08:02 27246                      /usr/lib/libstreamanalyzer.so.0.7.7
7f0311c97000-7f0311e96000 ---p 0007a000 08:02 27246                      /usr/lib/libstreamanalyzer.so.0.7.7
7f0311e96000-7f0311e99000 r--p 00079000 08:02 27246                      /usr/lib/libstreamanalyzer.so.0.7.7
7f0311e99000-7f0311e9a000 rw-p 0007c000 08:02 27246                      /usr/lib/libstreamanalyzer.so.0.7.7
7f0311e9a000-7f0311e9b000 rw-p 00000000 00:00 0 
7f0311e9b000-7f0311e9c000 r-xp 00000000 08:02 21327                      /usr/lib/libutempter.so.1.1.5
7f0311e9c000-7f031209c000 ---p 00001000 08:02 21327                      /usr/lib/libutempter.so.1.1.5
7f031209c000-7f031209d000 r--p 00001000 08:02 21327                      /usr/lib/libutempter.so.1.1.5
7f031209d000-7f031209e000 rw-p 00002000 08:02 21327                      /usr/lib/libutempter.so.1.1.5
7f031209e000-7f03120d6000 r-xp 00000000 08:02 27267                      /usr/lib/libnepomukutils.so.4.8.0
7f03120d6000-7f03122d6000 ---p 00038000 08:02 27267                      /usr/lib/libnepomukutils.so.4.8.0
7f03122d6000-7f03122d8000 r--p 00038000 08:02 27267                      /usr/lib/libnepomukutils.so.4.8.0
7f03122d8000-7f03122d9000 rw-p 0003a000 08:02 27267                      /usr/lib/libnepomukutils.so.4.8.0
7f03122d9000-7f03123ae000 r-xp 00000000 08:02 27296                      /usr/lib/libnepomuk.so.4.8.0
7f03123ae000-7f03125ad000 ---p 000d5000 08:02 27296                      /usr/lib/libnepomuk.so.4.8.0
7f03125ad000-7f03125b0000 r--p 000d4000 08:02 27296                      /usr/lib/libnepomuk.so.4.8.0
7f03125b0000-7f03125b1000 rw-p 000d7000 08:02 27296                      /usr/lib/libnepomuk.so.4.8.0
7f03125b1000-7f03125e4000 r-xp 00000000 08:02 17098                      /usr/lib/x86_64-linux-gnu/libdbusmenu-qt.so.2.6.0
7f03125e4000-7f03127e3000 ---p 00033000 08:02 17098                      /usr/lib/x86_64-linux-gnu/libdbusmenu-qt.so.2.6.0
7f03127e3000-7f03127e4000 r--p 00032000 08:02 17098                      /usr/lib/x86_64-linux-gnu/libdbusmenu-qt.so.2.6.0
7f03127e4000-7f03127e5000 rw-p 00033000 08:02 17098                      /usr/lib/x86_64-linux-gnu/libdbusmenu-qt.so.2.6.0
7f03127e5000-7f03128ce000 r-xp 00000000 08:02 27215                      /usr/lib/libattica.so.0.3.0
7f03128ce000-7f0312ace000 ---p 000e9000 08:02 27215                      /usr/lib/libattica.so.0.3.0
7f0312ace000-7f0312ad2000 r--p 000e9000 08:02 27215                      /usr/lib/libattica.so.0.3.0
7f0312ad2000-7f0312ad3000 rw-p 000ed000 08:02 27215                      /usr/lib/libattica.so.0.3.0
7f0312ad3000-7f0312d73000 r-xp 00000000 08:02 27332                      /usr/lib/libkio.so.5.8.0
7f0312d73000-7f0312f73000 ---p 002a0000 08:02 27332                      /usr/lib/libkio.so.5.8.0
7f0312f73000-7f0312f85000 r--p 002a0000 08:02 27332                      /usr/lib/libkio.so.5.8.0
7f0312f85000-7f0312f8a000 rw-p 002b2000 08:02 27332                      /usr/lib/libkio.so.5.8.0
7f0312f8a000-7f0312f8b000 rw-p 00000000 00:00 0 
7f0312f8b000-7f0312f93000 r-xp 00000000 08:02 27283                      /usr/lib/libkpty.so.4.8.0
7f0312f93000-7f0313193000 ---p 00008000 08:02 27283                      /usr/lib/libkpty.so.4.8.0
7f0313193000-7f0313194000 r--p 00008000 08:02 27283                      /usr/lib/libkpty.so.4.8.0
7f0313194000-7f0313195000 rw-p 00009000 08:02 27283                      /usr/lib/libkpty.so.4.8.0
7f0313195000-7f03135ce000 r-xp 00000000 08:02 27294                      /usr/lib/libkdeui.so.5.8.0
7f03135ce000-7f03137cd000 ---p 00439000 08:02 27294                      /usr/lib/libkdeui.so.5.8.0
7f03137cd000-7f03137f6000 r--p 00438000 08:02 27294                      /usr/lib/libkdeui.so.5.8.0
7f03137f6000-7f03137fd000 rw-p 00461000 08:02 27294                      /usr/lib/libkdeui.so.5.8.0
7f03137fd000-7f03137ff000 rw-p 00000000 00:00 0 
7f03137ff000-7f0313800000 ---p 00000000 00:00 0 
7f0313800000-7f0314000000 rw-p 00000000 00:00 0 
7f0314000000-7f0315da1000 rw-p 00000000 00:00 0 
7f0315da1000-7f0318000000 ---p 00000000 00:00 0 
7f0318068000-7f03180b6000 r-xp 00000000 08:02 27265                      /usr/lib/libkparts.so.4.8.0
7f03180b6000-7f03182b6000 ---p 0004e000 08:02 27265                      /usr/lib/libkparts.so.4.8.0
7f03182b6000-7f03182ba000 r--p 0004e000 08:02 27265                      /usr/lib/libkparts.so.4.8.0
7f03182ba000-7f03182bb000 rw-p 00052000 08:02 27265                      /usr/lib/libkparts.so.4.8.0
7f03182bb000-7f03183a7000 r-xp 00000000 08:02 27241                      /usr/lib/libkde3support.so.4.8.0
7f03183a7000-7f03185a6000 ---p 000ec000 08:02 27241                      /usr/lib/libkde3support.so.4.8.0
7f03185a6000-7f03185b1000 r--p 000eb000 08:02 27241                      /usr/lib/libkde3support.so.4.8.0
7f03185b1000-7f03185b4000 rw-p 000f6000 08:02 27241                      /usr/lib/libkde3support.so.4.8.0
7f03185b4000-7f03185bb000 r-xp 00000000 08:02 27331                      /usr/lib/qt4/plugins/designer/kde3supportwidgets.so
7f03185bb000-7f03187bb000 ---p 00007000 08:02 27331                      /usr/lib/qt4/plugins/designer/kde3supportwidgets.so
7f03187bb000-7f03187bc000 r--p 00007000 08:02 27331                      /usr/lib/qt4/plugins/designer/kde3supportwidgets.so
7f03187bc000-7f03187bd000 rw-p 00008000 08:02 27331                      /usr/lib/qt4/plugins/designer/kde3supportwidgets.so
7f03187bd000-7f0318ce8000 r-xp 00000000 08:02 4365                       /usr/lib/x86_64-linux-gnu/libQtDesigner.so.4.8.1
7f0318ce8000-7f0318ee8000 ---p 0052b000 08:02 4365                       /usr/lib/x86_64-linux-gnu/libQtDesigner.so.4.8.1
7f0318ee8000-7f0318f00000 r--p 0052b000 08:02 4365                       /usr/lib/x86_64-linux-gnu/libQtDesigner.so.4.8.1Aborted (core dumped)

**Comment by ablasdel** [comment]
Did you ever see this again Austin?

**Comment by ahendrix** [comment]
I'm not sure. The dashboard still crashes occasionally, but I don't run it in gdb, so I can't usually tell why it crashed.

In general, dashboard crashes aren't a big problem any more.
