### ISSUE TITLE
Catkinize

### ISSUE THREAD

**Issue by 130s** [PR2/rqt_pr2_dashboard#8]
If I understand the diagram from `rqt_dep` correctly, only 2 pkgs are left dry and no dry pkgs in the further upstream dependency?
![snap_dep_pr2_dashboard](https://f.cloud.github.com/assets/1840401/277869/1e4f1796-90d4-11e2-9f52-88c6857650fe.png)

**Comment by ablasdel** [comment]
That is correct. Once those pr2 packages are catkinized rqt_pr2_dashboard
can also be catkinized.

**Comment by 130s** [comment]
Looks like all the upstream pkgs are already wet. I'll try to catkinize this within a day.

**Comment by 130s** [comment]
Done via https://github.com/ros-visualization/rqt_pr2_dashboard/pull/10
